import {
  Activity,
  AlarmClock,
  Archive,
  BarChart3,
  Blocks,
  BriefcaseBusiness,
  Building2,
  CalendarDays,
  PoundSterling,
  ContactRound,
  FileSignature,
  FolderKanban,
  FolderOpen,
  HeartHandshake,
  Inbox,
  LayoutDashboard,
  ListChecks,
  MailPlus,
  Radar,
  ReceiptText,
  Settings2,
  Timer,
  UsersRound,
  Workflow,
} from "lucide-react";

export const navigation = [
  {
    label: "Command",
    items: [
      { label: "Today", path: "/", icon: LayoutDashboard },
      { label: "Inbox", path: "/inbox", icon: Inbox },
      { label: "Calendar", path: "/calendar", icon: CalendarDays },
    ],
  },
  {
    label: "CRM",
    items: [
      { label: "Accounts", path: "/accounts", icon: Building2 },
      { label: "Contacts", path: "/contacts", icon: ContactRound },
    ],
  },
  {
    label: "Revenue",
    items: [
      { label: "Pipeline", path: "/pipeline", icon: BriefcaseBusiness },
      { label: "Tender Radar", path: "/tenders", icon: Radar },
      { label: "Sequences", path: "/sequences", icon: MailPlus },
    ],
  },
  {
    label: "Delivery",
    items: [
      { label: "Projects", path: "/projects", icon: FolderKanban },
      { label: "Time", path: "/time", icon: Timer },
    ],
  },
  {
    label: "Commercial",
    items: [
      { label: "Proposals & contracts", path: "/proposals", icon: FileSignature },
      { label: "Billing", path: "/billing", icon: PoundSterling },
      { label: "Client success", path: "/client-success", icon: HeartHandshake },
    ],
  },
  {
    label: "Control",
    items: [
      { label: "Reports", path: "/reports", icon: BarChart3 },
      { label: "Automations", path: "/automations", icon: Workflow },
    ],
  },
  {
    label: "System",
    items: [
      { label: "Files", path: "/files", icon: FolderOpen },
      { label: "Settings", path: "/settings", icon: Settings2 },
    ],
  },
];

export const allNavigationItems = navigation.flatMap((group) => group.items);

export const resourceConfigs = {
  accounts: {
    title: "Accounts",
    singular: "account",
    endpoint: "accounts",
    path: "/accounts",
    icon: Building2,
    description: "The organisation hub for every relationship, deal, project and balance.",
    fields: [
      ["Lifecycle", "lifecycle_status", "status"],
      ["Domain", "domain", "website"],
      ["Owner", "owner_name", "owner"],
      ["Next action", "next_action"],
    ],
    editableFields: [
      { key: "name", label: "Account name", editor: "text", required: true },
      { key: "status", label: "Lifecycle", editor: "select", options: ["Prospect", "Client", "Dormant"] },
      { key: "health_status", label: "Health", editor: "select", options: ["Healthy", "Watch", "At risk"] },
      { key: "renewal_date", label: "Renewal", editor: "date" },
      { key: "domain", label: "Domain", editor: "text" },
      { key: "notes", label: "Notes", editor: "textarea" },
    ],
  },
  contacts: {
    title: "Contacts",
    singular: "contact",
    endpoint: "contacts",
    path: "/contacts",
    icon: UsersRound,
    description: "People, their roles, communication history and linked organisations.",
    fields: [
      ["Account", "account_name", "company"],
      ["Role", "job_title", "role"],
      ["Email", "email"],
      ["Last contact", "last_contact_at", "last_contact"],
    ],
    editableFields: [
      { key: "display_name", label: "Display name", editor: "text", required: true },
      { key: "job_title", label: "Role", editor: "text" },
      { key: "email", label: "Email", editor: "email", emptyValue: null },
      { key: "phone", label: "Phone", editor: "tel" },
      { key: "status", label: "Status", editor: "select", options: ["Active", "Inactive"] },
      { key: "notes", label: "Notes", editor: "textarea" },
    ],
  },
  leads: {
    title: "Leads",
    singular: "lead",
    endpoint: "leads",
    path: "/leads",
    icon: Activity,
    description: "Early opportunities waiting for qualification or nurture.",
    fields: [
      ["Status", "status"],
      ["Company", "company_name", "company"],
      ["Source", "source"],
      ["Next action", "next_action"],
    ],
    editableFields: [
      { key: "title", label: "Lead name", editor: "text", required: true },
      { key: "company", label: "Company", editor: "text" },
      { key: "status", label: "Status", editor: "select", options: ["New", "Working", "Qualified", "Nurture", "Disqualified"] },
      { key: "score", label: "Score", editor: "number", min: 0, max: 100 },
      { key: "estimated_value_minor", label: "Estimated value", editor: "money", min: 0 },
      { key: "next_action", label: "Next action", editor: "text" },
      { key: "notes", label: "Notes", editor: "textarea" },
    ],
  },
  tenders: {
    title: "Tender Radar",
    singular: "tender",
    endpoint: "tenders",
    path: "/tenders",
    icon: Radar,
    description: "Evidence-backed public opportunities, ranked by fit and deadline.",
    fields: [
      ["Buyer", "buyer_name", "organisation"],
      ["Deadline", "deadline_at", "deadline"],
      ["Fit", "fit_score", "score"],
      ["Status", "triage_status", "status"],
    ],
  },
  opportunities: {
    title: "Deals",
    singular: "deal",
    endpoint: "opportunities",
    path: "/opportunities",
    icon: BriefcaseBusiness,
    description: "Qualified revenue through discovery, proposal, contract and close.",
    fields: [
      ["Stage", "stage_name", "stage", "status"],
      ["Account", "account_name"],
      ["Value", "value_minor", "amount_minor"],
      ["Close", "expected_close_at", "expected_close"],
    ],
    editableFields: [
      { key: "title", label: "Deal name", editor: "text", required: true },
      { key: "type", label: "Type", editor: "text" },
      { key: "value_minor", label: "Value", editor: "money", min: 0 },
      { key: "probability_bps", label: "Probability", editor: "percent", min: 0, max: 100 },
      { key: "expected_close_date", label: "Expected close", editor: "date" },
      { key: "next_action", label: "Next action", editor: "text" },
      { key: "notes", label: "Notes", editor: "textarea" },
    ],
  },
  sequences: {
    title: "Sequences",
    singular: "sequence",
    endpoint: "sequences",
    path: "/sequences",
    icon: MailPlus,
    description: "Measured outreach that pauses on replies, bounces and opt-outs.",
    fields: [
      ["Status", "state", "status"],
      ["Enrolled", "enrollment_count", "enrolled_count"],
      ["Daily cap", "daily_cap"],
      ["Last activity", "last_activity_at", "updated_at"],
    ],
  },
  projects: {
    title: "Projects",
    singular: "project",
    endpoint: "projects",
    path: "/projects",
    icon: FolderKanban,
    description: "Delivery plans, milestones, work, cost and commercial context.",
    fields: [
      ["Status", "status"],
      ["Account", "account_name"],
      ["Progress", "progress_percent", "progress"],
      ["Next milestone", "next_milestone_at", "due_at"],
    ],
    editableFields: [
      { key: "name", label: "Project name", editor: "text", required: true },
      { key: "status", label: "Status", editor: "select", options: ["Planned", "Active", "Blocked", "Complete", "Cancelled"] },
      { key: "billing_type", label: "Billing", editor: "select", options: ["fixed", "milestone", "hourly", "retainer"] },
      { key: "budget_pence", label: "Budget", editor: "money", min: 0 },
      { key: "starts_on", label: "Starts", editor: "date" },
      { key: "due_on", label: "Due", editor: "date" },
      { key: "notes", label: "Notes", editor: "textarea" },
    ],
  },
  milestones: {
    title: "Milestones",
    singular: "milestone",
    endpoint: "milestones",
    path: "/milestones",
    icon: AlarmClock,
    description: "Dated delivery checkpoints within a project.",
    fields: [["Status", "status"], ["Due", "due_on", "due_at"], ["Project", "project_name"], ["Owner", "owner_name"]],
    editableFields: [
      { key: "title", label: "Milestone", editor: "text", required: true },
      { key: "status", label: "Status", editor: "select", options: ["Planned", "In progress", "Complete", "Cancelled"] },
      { key: "due_on", label: "Due", editor: "date" },
      { key: "amount_pence", label: "Billing amount", editor: "money", min: 0 },
    ],
  },
  "time-entries": {
    title: "Time",
    singular: "time entry",
    endpoint: "time-entries",
    path: "/time",
    icon: Timer,
    description: "Billable and internal time, connected directly to delivery.",
    fields: [
      ["Project", "project_name"],
      ["Date", "entry_date", "date"],
      ["Duration", "minutes", "duration_minutes"],
      ["Billing", "billing_status", "billable"],
    ],
    editableFields: [
      { key: "entry_date", label: "Date", editor: "date", required: true },
      { key: "minutes", label: "Minutes", editor: "number", min: 1, max: 1440, required: true },
      { key: "description", label: "Description", editor: "textarea" },
      { key: "billable", label: "Billable", editor: "checkbox" },
      { key: "hourly_rate_pence", label: "Hourly rate", editor: "money", min: 0 },
    ],
  },
  expenses: {
    title: "Expenses",
    singular: "expense",
    endpoint: "expenses",
    path: "/expenses",
    icon: ReceiptText,
    description: "Project costs connected to profitability and billing.",
    fields: [["Project", "project_name"], ["Date", "expense_date", "date"], ["Amount", "amount_pence", "amount_minor"], ["Billing", "billable"]],
  },
  proposals: {
    title: "Proposals",
    singular: "proposal",
    endpoint: "proposals",
    path: "/proposals",
    icon: FileSignature,
    description: "Versioned offers built from the service catalogue.",
    fields: [
      ["Number", "number", "proposal_number"],
      ["Account", "account_name"],
      ["Value", "total_pence", "total_minor", "value_minor"],
      ["Status", "status"],
    ],
    editableWhen: (record) => record.status === "Draft",
    editableFields: [
      { key: "title", label: "Proposal title", editor: "text", required: true },
      { key: "valid_until", label: "Valid until", editor: "date" },
      { key: "notes", label: "Notes", editor: "textarea" },
    ],
  },
  contracts: {
    title: "Contracts",
    singular: "contract",
    endpoint: "contracts",
    path: "/contracts",
    icon: FileSignature,
    description: "Signed scope, dates and immutable commercial versions.",
    fields: [
      ["Number", "number", "contract_number"],
      ["Account", "account_name"],
      ["Value", "value_pence", "value_minor"],
      ["Status", "status"],
    ],
    editableWhen: (record) => record.status === "Draft",
    editableFields: [
      { key: "title", label: "Contract title", editor: "text", required: true },
      { key: "starts_on", label: "Starts", editor: "date" },
      { key: "ends_on", label: "Ends", editor: "date" },
      { key: "value_pence", label: "Value", editor: "money", min: 0 },
      { key: "notes", label: "Notes", editor: "textarea" },
    ],
  },
  invoices: {
    title: "Invoices",
    singular: "invoice",
    endpoint: "invoices",
    path: "/invoices",
    icon: ReceiptText,
    description: "Local legal invoices, payment status and immutable issue snapshots.",
    fields: [
      ["Number", "number", "invoice_number"],
      ["Account", "account_name"],
      ["Outstanding", "outstanding_pence", "outstanding_minor", "total_pence", "total_minor"],
      ["Status", "status"],
    ],
    editableWhen: (record) => record.status === "Draft",
    editableFields: [
      { key: "customer_name", label: "Customer", editor: "text", required: true },
      { key: "due_on", label: "Due", editor: "date", required: true },
      { key: "customer_address", label: "Address", editor: "textarea" },
      { key: "notes", label: "Notes", editor: "textarea" },
    ],
  },
  "credit-notes": {
    title: "Credit notes",
    singular: "credit note",
    endpoint: "credit-notes",
    path: "/credit-notes",
    icon: ReceiptText,
    description: "Immutable invoice corrections with reversing ledger entries.",
    fields: [
      ["Number", "number"],
      ["Invoice", "invoice_id"],
      ["Value", "total_pence"],
      ["Status", "status"],
    ],
  },
  payments: {
    title: "Payments",
    singular: "payment",
    endpoint: "payments",
    path: "/payments",
    icon: PoundSterling,
    description: "Receipts, allocations, clearing and reconciliation.",
    fields: [
      ["Reference", "reference", "provider_reference"],
      ["Account", "account_name"],
      ["Amount", "amount_pence", "amount_minor"],
      ["Received", "received_at", "created_at"],
    ],
  },
  "client-success": {
    title: "Client success",
    singular: "client health record",
    endpoint: "client-success",
    path: "/client-success",
    icon: HeartHandshake,
    description: "Health, risk, reviews and renewals across active accounts.",
    fields: [
      ["Health", "computed_health", "health", "health_status"],
      ["Account", "account_name", "name"],
      ["Next review", "next_review_on", "next_review_at", "review_date"],
      ["Renewal", "renewal_on", "renewal_at", "renewal_date"],
    ],
  },
  automations: {
    title: "Automations",
    singular: "automation",
    endpoint: "automations",
    path: "/automations",
    icon: Workflow,
    description: "Versioned rules with previews, approvals and an execution trail.",
    fields: [
      ["Trigger", "trigger_type", "trigger"],
      ["Status", "status", "enabled"],
      ["Runs", "execution_count", "run_count"],
      ["Last run", "last_run_at"],
    ],
  },
  files: {
    title: "Files",
    singular: "file",
    endpoint: "documents",
    path: "/files",
    icon: FolderOpen,
    description: "Drive-backed working files and checksummed issued versions.",
    fields: [
      ["Type", "mime_type", "document_type"],
      ["Linked to", "account_name", "related_name"],
      ["Version", "version"],
      ["Updated", "updated_at"],
    ],
  },
  tasks: {
    title: "Tasks",
    singular: "task",
    endpoint: "tasks",
    path: "/tasks",
    icon: ListChecks,
    description: "Follow-ups and next actions across the workspace.",
    fields: [
      ["Due", "due_at", "due_date"],
      ["Priority", "priority"],
      ["Linked to", "related_name"],
      ["Status", "status"],
    ],
    editableFields: [
      { key: "title", label: "Task", editor: "text", required: true },
      { key: "status", label: "Status", editor: "select", options: ["Open", "In progress", "Done", "Cancelled"] },
      { key: "priority", label: "Priority", editor: "select", options: ["Low", "Medium", "High"] },
      { key: "due_at", label: "Due", editor: "datetime-local" },
      { key: "description", label: "Description", editor: "textarea" },
    ],
  },
};

export const mobileNavigation = [
  allNavigationItems.find((item) => item.path === "/"),
  allNavigationItems.find((item) => item.path === "/inbox"),
  allNavigationItems.find((item) => item.path === "/pipeline"),
  allNavigationItems.find((item) => item.path === "/projects"),
];

export const dealStages = ["Discovery", "Qualified", "Contacted", "Meeting", "Proposal", "Negotiation", "Contract", "Won", "Lost"];

export const createTypes = [
  { value: "accounts", label: "Account", nameLabel: "Account name" },
  { value: "contacts", label: "Contact", nameLabel: "Full name" },
  { value: "leads", label: "Lead", nameLabel: "Lead name" },
  { value: "opportunities", label: "Deal", nameLabel: "Deal name" },
  { value: "tasks", label: "Task", nameLabel: "Task title" },
];

export const quickPages = allNavigationItems.map((item) => ({
  id: `page-${item.path}`,
  title: item.label,
  subtitle: "Go to page",
  path: item.path,
  icon: item.icon,
}));

export const statusOptions = {
  accounts: ["Prospect", "Client", "Dormant"],
  leads: ["New", "Working", "Qualified", "Nurture", "Disqualified"],
  tenders: ["New", "Reviewing", "Qualified", "Rejected", "Snoozed", "Expired"],
  opportunities: ["Open", "Won", "Lost"],
  tasks: ["Open", "In progress", "Done", "Cancelled"],
  projects: ["Planned", "Active", "Blocked", "Complete", "Cancelled"],
  milestones: ["Planned", "In progress", "Complete", "Cancelled"],
  proposals: ["Draft", "Sent", "Accepted", "Rejected", "Expired", "Void"],
  contracts: ["Draft", "Sent", "Signed", "Active", "Expired", "Terminated"],
  invoices: ["Draft", "Sent", "Part-paid", "Paid", "Overdue", "Void"],
  "client-success": ["Healthy", "Watch", "At risk"],
};

export const utilityIcons = { AlarmClock, Archive, Blocks };
